### ISSUE TITLE
A new version is saved even though no changes have been made

### ISSUE THREAD

**Issue by agoat** [contao/news-bundle#26]
I noticed that every time you save, a new version is created, although it hasn't been changed.

It looks like the adjustTime callback handling the date and time input is causing this behaviour. 
When the form is submitted, the dc_table driver will first save the timestamps for each of these fields and the onsubmit_callback will add the two timestamp together and saves them again. 
This result in an always different timestamp when loading the form and when saving (e.g. the time input only return and save the seconds from midnight to the entered hours and minutes).

This is the same in the calendar-bundle when time is added.

I don't know a solution right now. One solution could be to use a single field with 'regx'=>'datim'. But that is not user friendly when time is not relevant.

**Comment by leofeyer** [comment]
Does https://github.com/contao/core-bundle/pull/1184 also fix this issue?

**Comment by leofeyer** [comment]
Fixed in 0f516ace912beb62e680b92bf8efd87644195369.

**Comment by agoat** [comment]
In my extension I found a (not perfect) solution where I wanted to have a separate input of date and time:

I simply added a load and save callback and adjusted the timestamp to match the expected values. (see also https://github.com/agoat/contao-postsnpages-bundle/blob/master/src/Resources/contao/dca/tl_posts.php#L238-L274)
```php
	// Fields
	'fields' => array
	(
		'date' => array
		(
			// ..
			'load_callback' => array
			(
				array('class', 'loadDate')
			),
			'save_callback' => array
			(
				array('class', 'resetTime')
			),
			// ..
			
		'time' => array
		(
			// ..
			'load_callback' => array
			(
				array('class', 'loadDate')
			),
			'save_callback' => array
			(
				array('class', 'resetTime')
			),
			// ..

			
	// ..
	
	
	/**
	 * Reduce the tstamp to contain only the date tstamp
	 *
	 * @param integer $value
	 *
	 * @return integer
	 */
	public function loadDate($value)
	{
		$objDate = new \Date(date('Y-m-d', $value), 'Y-m-d');
		return $objDate->tstamp;
	}
		
	/**
	 * Reduce the tstamp to contain only the time tstamp
	 *
	 * @param integer $value
	 *
	 * @return integer
	 */
	public function loadTime($value)
	{
		$objDate = new \Date(date('H:i:s', $value), 'H:i:s');
		return $objDate->tstamp;
	}
		
	/**
	 * Reset the date and/or time to the current time if empty
	 *
	 * @param integer $value
	 *
	 * @return integer
	 */
	public function resetTime($value)
	{
		return empty($value) ? time() : $value;
	}

	```

**Comment by fritzmg** [comment]
@agoat this way you have to use two separate variables in order to display the date _and_ time in the front end.

**Comment by agoat** [comment]
No. The `onsubmit_callback` is still present and adjusts both fields.

**Comment by fritzmg** [comment]
Ah, I see.

**Comment by leofeyer** [comment]
Fixed in 440e9f29eba45aee71994b2a1618feb548d620b2.

**Comment by leofeyer** [comment]
@agoat I didn't see your solution until right now. I will give it a try.

**Comment by leofeyer** [comment]
I have implemented your solution in e591ee4d8cf9d1ee9e73a9a5ed97af7ef78609e4.
